package com.axelor.qpack;// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.Assertions.*;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.*;
import java.util.concurrent.TimeUnit;

@Disabled
public class AddRecordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    if (driver != null)
      driver.quit();
  }

  @Test
  public void TestAddRecord() {
    driver.get("http://localhost:8080/nsqr-analytics-module/login.jsp");
    driver.manage().timeouts().setScriptTimeout(5L, TimeUnit.SECONDS);
    driver.manage().timeouts().implicitlyWait(5L, TimeUnit.SECONDS);

    driver.manage().window().setSize(new Dimension(1375, 927));
    driver.findElement(By.id("usernameId")).click();
    driver.findElement(By.id("usernameId")).sendKeys("admin");
    driver.findElement(By.id("passwordId")).sendKeys("admin");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".nav-tree > .ng-scope:nth-child(3) > a .nav-title")).click();
    driver.findElement(By.cssSelector(".nav:nth-child(3) > .ng-scope:nth-child(3) > .nav .nav-title")).click();
    driver.findElement(By.cssSelector(".fa-plus")).click();
    WebDriverWait wait = new WebDriverWait(driver,130);
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#\\_formWidget3 > .ng-scope")));
    driver.findElement(By.cssSelector("#\\_formWidget3 > .ng-scope")).click();
    driver.findElement(By.cssSelector("#\\_formWidget3 > .ng-scope")).sendKeys("testExecutor");
    driver.findElement(By.cssSelector("a:nth-child(2) > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("a:nth-child(2) > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#\\_formWidget13 > .ng-scope")).sendKeys("testIdentity");
    driver.findElement(By.cssSelector("#\\_formWidget14 > .ng-scope")).sendKeys("testName");
    driver.findElement(By.cssSelector("#\\_formWidget15 > .ng-scope")).sendKeys("testClassification");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".btn > .fa-floppy-o")).click();
    driver.findElement(By.cssSelector(".fa-reply")).click();
    driver.findElement(By.cssSelector(".fa-reply")).click();

    //driver.findElement(By.cssSelector(".slick-cell:nth-child(2)")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".slick-cell:nth-child(2)")));
    //driver.findElement(By.cssSelector(".slick-cell:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".slick-cell:nth-child(2)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".slick-cell:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".l1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".l1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".l1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".l1")).click();
    driver.findElement(By.cssSelector(".l1")).click();
    driver.findElement(By.cssSelector(".l1")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".l1"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("#\\_formWidget13 > .display-text")).click();
    driver.findElement(By.cssSelector("#\\_formWidget13 > .display-text")).click();
    {
      //WebElement element = driver.findElement(By.cssSelector("#\\_formWidget13 > .display-text"));
      WebElement element = driver.findElement(By.name("identity"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("#\\_formWidget15 > .display-text")).click();
    driver.findElement(By.cssSelector("#\\_formWidget15 > .display-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#\\_formWidget15 > .display-text"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("#\\_formWidget14 > .display-text")).click();
    driver.findElement(By.cssSelector("#\\_formWidget14 > .display-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#\\_formWidget14 > .ng-scope"));
      //WebElement element = driver.findElement(By.name("identity"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
      String value = element.getText();
      assertEquals("testIdentity", value);

    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".fa-user")).click();
    driver.findElement(By.linkText("Log out")).click();
  }
}
