package com.axelor.qpack;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class CreateRecordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;


  @BeforeEach
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/test/resources/drivers/chromedriver");
    ChromeOptions options = new ChromeOptions();
    options.setHeadless(true);
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }


  @Test
  public void TestCreateRecord() {
    driver.manage().timeouts().setScriptTimeout(10L, TimeUnit.SECONDS);
    driver.manage().timeouts().implicitlyWait(10L, TimeUnit.SECONDS);

    //Arrange
    driver.get("http://localhost:8080/nsqr-analytics-module/login.jsp");
    driver.manage().window().setSize(new Dimension(1920, 1048));
    driver.findElement(By.id("usernameId")).sendKeys("admin");
    driver.findElement(By.id("passwordId")).sendKeys("admin");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Analytics")).click();
    driver.findElement(By.cssSelector(".nav:nth-child(3) > .ng-scope:nth-child(3) > .nav .nav-title")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".nav:nth-child(3) > .ng-scope:nth-child(3) > .nav .nav-title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".fa-plus")).click();
    driver.findElement(By.cssSelector("a > .fa-plus")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("a > .fa-plus"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#\\_formWidget15 > .ng-scope")).click();
    driver.findElement(By.cssSelector("#\\_formWidget15 > .ng-scope")).sendKeys("TESTClassification");
    driver.findElement(By.cssSelector("#\\_formWidget14 > .ng-scope")).sendKeys("TestName");
    driver.findElement(By.cssSelector("#\\_formWidget13 > .ng-scope")).sendKeys("TestIdentity");
    driver.findElement(By.cssSelector(".btn-primary")).click();

    //Act
    driver.findElement(By.cssSelector("#\\_formWidget3 > .ng-scope")).click();
    driver.findElement(By.cssSelector("#\\_formWidget3 > .ng-scope")).sendKeys("TestExecutor");
    driver.findElement(By.cssSelector("#\\_formWidget4 > .ng-scope")).sendKeys("TestModel");
    driver.findElement(By.cssSelector(".btn-group > .ng-scope:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".fa-reply")).click();
    driver.findElement(By.cssSelector(".l1")).click();
    driver.findElement(By.cssSelector(".l1")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".l1"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }

    //Assert
    Assertions.assertEquals("TESTClassification", driver.findElement(By.cssSelector("#\\_formWidget15 > .ng-scope")).getAttribute("value"));
    Assertions.assertEquals("TestName", driver.findElement(By.cssSelector("#\\_formWidget14 > .ng-scope")).getAttribute("value"));
    Assertions.assertEquals("TestIdentity", driver.findElement(By.cssSelector("#\\_formWidget13 > .ng-scope")).getAttribute("value"));

    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector(".nav-link-user")).click();
    driver.findElement(By.linkText("Log out")).click();
  }
}
